name: Prettier

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v3

      - name: Install Prettier
        run: npm i -g prettier

      - name: Format codebase
        run: prettier -w .

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ github.token }}
          commit-message: "style: prettier [skip ci]"
          author: "github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"
          branch: fmt/prettier
          delete-branch: true
          title: "style: prettier"
          labels: ci:style
