name: Cargo clippy

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install nanomsg
        run: bash scripts/ci_install_nanomsg.sh
      - name: Check coding style
        run: |
          cargo clippy --workspace
